# Generated by Django 4.2.4 on 2023-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
