# Generated by Django 4.2.4 on 2023-12-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='language',
        ),
    ]
