# Generated by Django 4.2.4 on 2023-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0002_remove_addproduct_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
