# Generated by Django 4.2.4 on 2023-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0008_addproduct_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
