# Generated by Django 4.2.4 on 2023-12-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0010_alter_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=255)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx_management_app.category')),
            ],
        ),
    ]
