# Generated by Django 4.2.4 on 2024-01-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olx_management_app', '0012_addproduct_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olx_management_app.subcategory'),
        ),
    ]
